name: apolo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
isar_version: &isar_version 3.1.8 # Versión que se va a usar (esta es la última)

environment:
  sdk: ^3.5.4

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.4.1
  csv: ^6.0.0
  device_info_plus: ^11.1.1
  dio: ^5.7.0
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.0
  icons_plus: ^5.0.0
  image_picker: ^1.1.2
  isar:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  just_audio: ^0.9.42
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1

dev_dependencies:
  build_runner: any
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - assets/images/playlist_default.jpg

  # Fonts
  fonts:
    - family: Appbar
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
