name: apolo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
isar_version: &isar_version 3.1.8 # Versión que se va a usar (esta es la última)

environment:
  sdk: ^3.5.4

dependencies:
  animate_do: ^3.3.4
  audioplayers: ^6.1.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.0
  icons_plus: ^5.0.0
  isar:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/

dev_dependencies:
  build_runner: any
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/

flutter:
  uses-material-design: true
