name: Flutter Linux Packaging

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config \
            libgtk-3-dev liblzma-dev \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            dpkg  # Necesario para .deb
      
      - name: Build Linux (Release)
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release
      
      - name: Generate .deb package
        run: |
          mkdir -p deb_package/usr/local/bin
          cp -r build/linux/x64/release/bundle/* deb_package/usr/local/bin/
          dpkg-deb --build deb_package local_api_server_${{ github.ref_name }}.deb
      
      - name: Generate AppImage
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            --executable build/linux/x64/release/bundle/your_app \
            --desktop-file build/linux/x64/release/bundle/your_app.desktop \
            --output appimage
          mv *.AppImage local_api_server_${{ github.ref_name }}.AppImage
      
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            local_api_server_${{ github.ref_name }}.deb
            local_api_server_${{ github.ref_name }}.AppImage
