name: Flutter Linux Packaging - FinMusic

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: Get version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | tr -d '"')
          echo "Extracted version: $VERSION"
          echo "::set-output name=version::$VERSION"
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config \
            libgtk-3-dev liblzma-dev \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            dpkg

      - name: Build Linux (Release)
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release

      - name: Generate .deb package
        run: |
          # Crear estructura de directorios
          mkdir -p deb_package/{usr/local/bin,usr/share/icons/hicolor/512x512/apps,usr/share/applications,DEBIAN}
      
          # Copiar archivos
          cp -r build/linux/x64/release/bundle/* deb_package/usr/local/bin/
          cp assets/icon.png deb_package/usr/share/icons/hicolor/512x512/apps/finmusic.png
      
          # Archivo .desktop
          cat > deb_package/usr/share/applications/finmusic.desktop <<'EOL'
          [Desktop Entry]
          Name=FinMusic
          Exec=/usr/local/bin/finmusic
          Icon=finmusic
          Type=Application
          Categories=Audio;Music;
          EOL
          
          # Archivo control con versión del pubspec.yaml
          cat > deb_package/DEBIAN/control <<EOL
          Package: finmusic
          Version: ${{ steps.version.outputs.version }}
          Section: sound
          Priority: optional
          Architecture: amd64
          Maintainer: Pablo <pereacampospablo@gmail.com>
          Description: Reproductor de música FinMusic
          Depends: libgtk-3-0, liblzma5, gstreamer1.0-plugins-base
          EOL
    
          # Build .deb
          dpkg-deb --build deb_package finmusic_${{ steps.version.outputs.version }}.deb

      - name: Generate AppImage
        run: |
          # 1. Identificar el ejecutable
          EXECUTABLE="FinMusic"  # Nombre exacto del binario
          echo "Ejecutable: $EXECUTABLE"
      
          # 2. Crear archivo .desktop CORRECTAMENTE FORMATEADO
          DESKTOP_FILE="build/linux/x64/release/bundle/$EXECUTABLE.desktop"
          mkdir -p "$(dirname "$DESKTOP_FILE")"
          
          # ¡Importante! Sin indentación en el contenido EOL
          cat > "$DESKTOP_FILE" << 'EOL'
            [Desktop Entry]
            Name=FinMusic
            Exec=FinMusic
            Icon=finmusic
            Type=Application
            Categories=Audio;Music;
            EOL
      
          # 3. Configurar paths para icono
          ICON_FILE="build/linux/x64/release/bundle/data/flutter_assets/assets/icon.png"
          if [ ! -f "$ICON_FILE" ]; then
            echo "⚠️ Icono no encontrado en $ICON_FILE, buscando alternativas..."
            ICON_FILE=$(find build/linux/x64/release/bundle -name icon.png | head -n1)
            [ -z "$ICON_FILE" ] && ICON_FILE="/dev/null"
          fi
      
          # 4. Generar AppImage
          wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
      
          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            --executable "build/linux/x64/release/bundle/$EXECUTABLE" \
            --desktop-file "$DESKTOP_FILE" \
            --icon-file "$ICON_FILE" \
            --output appimage
      
          # 5. Renombrar el archivo final
          VERSION=${{ steps.version.outputs.version }}
          mv *.AppImage "finmusic_$VERSION.AppImage"

      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: FinMusic ${{ steps.version.outputs.version }}
          files: |
            finmusic_${{ steps.version.outputs.version }}.deb
            finmusic_${{ steps.version.outputs.version }}.AppImage
          draft: false
          prerelease: false
          replace_assets: true
