name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK for Android
      if: matrix.os == 'ubuntu-latest'
      run: flutter build apk --release

    - name: Build DEB for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev
        flutter build linux --release
        mkdir -p build/deb
        cp -r build/linux/x64/release/bundle/* build/deb/
        cd build/deb
        dpkg-deb --build . ../flutter_app.deb

    - name: Build EXE for Windows
      if: matrix.os == 'windows-latest'
      run: flutter build windows --release

    - name: Upload APK
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Upload DEB
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: linux-deb
        path: build/flutter_app.deb

    - name: Upload EXE
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: windows-exe
        path: build/windows/runner/Release/flutter_app.exe
