name: Flutter Multi-Platform Build

on:
  push:
    tags:
      - "v*"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - name: Build APK
        run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - name: Build Linux .deb
        run: |
          flutter build linux --release
          # Empaquetar en .deb manualmente si hace falta
      - name: Upload .deb
        uses: actions/upload-artifact@v3
        with:
          name: app-release.deb
          path: path/to/app-release.deb

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - name: Build Windows .exe
        run: flutter build windows --release
      - name: Upload .exe
        uses: actions/upload-artifact@v3
        with:
          name: app-release.exe
          path: build\windows\runner\Release\appname.exe